tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "ansible"
brew "cmake"
brew "direnv"
brew "fd"
brew "gh"
brew "git"
brew "jq"
brew "mas"
brew "neovim"
brew "nodenv"
brew "postgresql"
brew "pyenv"
brew "the_silver_searcher"
brew "tmux"
brew "trash"
brew "tree"
brew "vim"
brew "zsh"
brew "zsh-completions"

# cask "dropbox"
# cask "1password"  installed manually
cask "alacritty"
cask "discord"
cask "divvy"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "keycastr"
cask "krisp"
cask "loom"
cask "slack"
cask "spotify"
cask "steam"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"
cask "zoom"

mas "XCode", id: 497799835
