# vim: set ft=zsh:ts=2:sts=2:sw=2:
###############################################################################
# Misc
###############################################################################
export UNAME=${$(uname -s):l}
export DOTFILES=$HOME/dotfiles
export WORKON_HOME=$HOME/.pyvirtualenvs # Virtualenv
export KEYTIMEOUT=1 # Reduce command line vim delay
export PROMPT_EOL_MARK='%' # https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol

if [[ ! -f /tmp/.ssh-agent-loaded ]]; then
  if [[ $UNAME == darwin ]]; then
    ssh-add --apple-use-keychain --apple-load-keychain
  fi
  touch /tmp/.ssh-agent-loaded
fi

###############################################################################
# Browser
###############################################################################
if [[ $UNAME == darwin ]]; then
  export BROWSER='open'
fi

###############################################################################
# Editors
###############################################################################
if (( $+commands[nvim] )); then
  export EDITOR='nvim'
  export VISUAL='nvim'
else
  export EDITOR='vim'
  export VISUAL='vim'
fi
export PAGER='less'

###############################################################################
# Language
###############################################################################
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export LANGUAGE='en_US.UTF-8'

###############################################################################
# Less
###############################################################################
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-g -i -M -R -S -w -z-4 -X -F'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

###############################################################################
# Paths
###############################################################################
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

if [[ -d ~/.zsh/completion ]]; then
  fpath=(~/.zsh/completion $fpath)
fi


if [[ -d $HOME/bin ]]; then
  path=($HOME/bin $path)
fi

if [[ $UNAME == darwin ]]; then
  # used by Homebrew
  path=(/usr/local/sbin $path)
  # Inlined `brew shellenv` — output is static, so we skip spawning Homebrew on every shell.
  # Regenerate these lines if Homebrew is reinstalled or its layout changes.
  export HOMEBREW_PREFIX="/opt/homebrew"
  export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
  export HOMEBREW_REPOSITORY="/opt/homebrew"
  path=(/opt/homebrew/bin /opt/homebrew/sbin $path)
  export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:"
  export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"
  fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
fi

export GOPATH="$HOME/go"
if [[ -n $GOPATH ]]; then
  path+=($GOPATH/bin)
fi

if [[ -d $HOME/.pyenv ]]; then
  export PYENV_SHIMS=$HOME/.pyenv/shims
  path=($PYENV_SHIMS $path)
fi

if [[ -d $HOME/.rbenv ]]; then
  export RBENV_SHIMS=$HOME/.rbenv/shims
  path=($RBENV_SHIMS $path)
fi

if [[ -d $HOME/.nodenv ]]; then
  export NODENV_SHIMS=$HOME/.nodenv/shims
  path=($NODENV_SHIMS $path)
fi

if [[ -d $DOTFILES/bin ]]; then
  path+=($DOTFILES/bin)
  [[ -d $DOTFILES/bin/$UNAME ]] && path+=($DOTFILES/bin/$UNAME)
fi

if [[ -d $HOME/.fzf/bin ]]; then
  path+=($HOME/.fzf/bin)
fi

if [[ -d $HOME/lib/anaconda3 ]]; then
  path+=($HOME/lib/anaconda3/bin)
fi
export RACK_ENV=development

if [[ -d $HOME/.local/bin ]]; then
  LOCAL_BIN="$HOME/.local/bin"
  path=($LOCAL_BIN $path)
fi

if [[ -d $HOME/.claude/local ]]; then
  path=($HOME/.claude/local $path)
fi

# rust
if [[ -f "$HOME/.cargo/env" ]]; then
  . "$HOME/.cargo/env"
fi
