#!/bin/sh
mkdir .git/tags_lock 2>/dev/null || exit 0
trap "rmdir .git/tags_lock; rm .git/tags.$$ 2>/dev/null" EXIT

ctags --tag-relative -R -f .git/tags.$$ --exclude=.git --languages=-sql,-javascript
mv .git/tags.$$ .git/tags
